// Code generated by "stringer -type HashMech -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MD5-0]
	_ = x[SHA256-1]
}

const _HashMech_name = "md5sha256"

var _HashMech_index = [...]uint8{0, 3, 9}

func (i HashMech) String() string {
	if i >= HashMech(len(_HashMech_index)-1) {
		return "HashMech(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HashMech_name[_HashMech_index[i]:_HashMech_index[i+1]]
}
